#
# Main configuration file
#

# / = = = = = = = = = = = = = = = = \
# |      LASTLOGINAPI SETTINGS      |
# \ = = = = = = = = = = = = = = = = /
lastloginapi:
  updates:
    # Check for updates, recommended. LastLoginAPI will check for updates when the server finish to load
    check: true
    # Send a message to admins if an update is available
    # To see the warning you have to give 'lastloginapi.updates' permission
    warn: true
    # Special tags:
    # => %version%     = New version found
    # => %thisversion% = Version installed
    warn-message: "&aNew version of LastLoginAPI found: %version% (Current: %thisversion%)"

  logging:
    # Enable debug messages
    debug: false
    save-file:
      # Save to file log messages
      enable: false
      # Format of messages
      format: "%date% [%time%] %message%\n"
      # Log file name
      file: "log.txt"


# / = = = = = = = = = = = = = = = = \
# |        STORAGE  SETTINGS        |
# \ = = = = = = = = = = = = = = = = /
storage:
  # What type of storage the plugin should use?
  # Database storage types:
  # => mysql      | [Remote] Save the data into a MySQL database
  # => sqlite     | [File]   Save the data into a SQLite database (default)
  database-storage-type: sqlite

  storage-settings:
    # General settings of SQL databases
    general-sql-settings:
      varchar-size: 255
      upgrade:
        save-old-table: true
        old-table-suffix: "_backup"
      tables:
        players: "lastloginapi_players"
        versions: "lastloginapi_versions"

    # SQLite settings
    sqlite:
      database-file: "database.db"

    # MySQL settings
    mysql:
      address: "localhost"
      port: "3306"
      database: "database"
      username: "username"
      password: "password"
      # Size of the connection pool
      pool-size: 10
      # Lifetime of each connection, in milliseconds (Default: 30 minutes = 1800000ms)
      connection-lifetime: 1800000
      # Property used to alert when the connection is not using a valid SSL certificate
      use-ssl: false
      # Charset used by tables
      charset: "utf8"


# / = = = = = = = = = = = = = = = = \
# |      PLACEHOLDERS SETTINGS      |
# \ = = = = = = = = = = = = = = = = /
placeholders:
  # Formats:
  # => format: The text to show when the player is offline
  # => online: The text to show when the player is online
  # => unknown: The text to show when a player isn't found
  # Elapsed:
  # %days%, %hours%, %minutes% and %seconds%
  name:
    # The name of the player
    format: "%name%"
    format-unknown: "Unknown"

  last-login-date:
    # Date of latest login
    format: "yyyy-MM-dd"
    format-online: "Online"
    format-unknown: "Unknown"

  last-login-elapsed:
    # Elapsed time since latest login
    format: "%days%d, %hours%h, %minutes%m"
    format-online: ""
    format-unknown: "Unknown"

  last-logout-date:
    # Date of latest logout
    format: "yyyy-MM-dd"
    format-unknown: "Unknown"

  last-logout-elapsed:
    # Elapsed time since latest logout
    format: "%days%d, %hours%h, %minutes%m"
    format-unknown: "Unknown"

dont-edit-this.version: 1